# Generated by Django 5.1.6 on 2025-03-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='cart_id',
            new_name='wishlist_id',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='cart',
            new_name='wishlist',
        ),
    ]
