# Generated by Django 5.1.6 on 2025-03-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation_variation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breadcrumbs',
            field=models.TextField(default='', help_text='Structured breadcrumbs for SEO navigation'),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(default='', help_text='Canonical URL to prevent duplicate content issues'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_text',
            field=models.CharField(default='', help_text='Alt text for product image (for SEO & accessibility)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(default='', help_text='Meta Description (Recommended: 150-320 characters)', max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='', help_text='Meta Title (Recommended: 60-70 characters)', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(default='', help_text='Open Graph Description (Recommended: 150-320 characters)', max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.URLField(default='', help_text='URL of the Open Graph Image (1200x630px recommended)'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(default='', help_text='Open Graph Title (Recommended: 60-100 characters)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='', help_text='Brand name for the product', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_gtin',
            field=models.CharField(default='', help_text='Global Trade Item Number (GTIN) for SEO', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_mpn',
            field=models.CharField(default='', help_text='Manufacturer Part Number (MPN) for SEO', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sku',
            field=models.CharField(default='', help_text='Product SKU (Unique identifier for products)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='robots_meta',
            field=models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', help_text='Control search engine indexing', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='schema_markup',
            field=models.TextField(default='', help_text='JSON-LD Schema markup for search engines'),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_description',
            field=models.TextField(default='', help_text='Twitter Card Description (Same as OG Description)', max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_image',
            field=models.URLField(default='', help_text='URL of the Twitter Card Image (1200x675px recommended)'),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_title',
            field=models.CharField(default='', help_text='Twitter Card Title (Same as OG Title)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(default='', help_text='Comma-separated keywords (Avoid keyword stuffing)'),
        ),
    ]
