# Generated by Django 5.1.6 on 2025-03-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_breadcrumbs_product_canonical_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='breadcrumbs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_alt_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='robots_meta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='schema_markup',
        ),
        migrations.RemoveField(
            model_name='product',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='twitter_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='twitter_title',
        ),
    ]
