# Generated by Django 5.1.6 on 2025-04-08 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_featured_categories_url'),
        ('store', '0004_remove_product_breadcrumbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.featured_categories'),
        ),
    ]
