# Generated by Django 5.1.5 on 2025-02-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
