# Generated by Django 5.1.6 on 2025-04-09 19:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_feature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_marquee',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Slider News'),
        ),
    ]
