# Generated by Django 5.1.5 on 2025-02-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210321_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
