# Generated by Django 5.1.5 on 2025-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('store', '0005_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupons',
            field=models.ManyToManyField(to='coupons.coupon'),
        ),
    ]
