# Generated by Django 5.1.5 on 2025-02-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_secondary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='before_discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=10),
        ),
    ]
