# Generated by Django 5.1.5 on 2025-02-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('store', '0006_product_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='coupons.coupon'),
        ),
    ]
