# Generated by Django 5.1.6 on 2025-04-09 19:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_product_marquee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_marquee',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Product Marquee'),
        ),
    ]
