# Generated by Django 5.2 on 2025-04-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_product_marquee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.TextField(default='', help_text='Comma-separated keywords (Avoid keyword stuffing)'),
        ),
    ]
