# Generated by Django 5.1.5 on 2025-02-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_before_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(default='', help_text='Comma(,) Seperated Keywords', max_length=400),
        ),
    ]
