# Generated by Django 5.1.6 on 2025-04-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, help_text='Upload a banner image for the blog.', null=True, upload_to='blog/banners/')),
                ('meta_title', models.CharField(default='', help_text='Meta Title (Recommended: 60-70 characters)', max_length=70)),
                ('meta_description', models.TextField(default='', help_text='Meta Description (Recommended: 150-320 characters)', max_length=320)),
                ('meta_keywords', models.TextField(default='', help_text='Comma-separated keywords (Avoid keyword stuffing)')),
            ],
        ),
    ]
