# Generated by Django 5.1.6 on 2025-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='page_title',
            field=models.CharField(default='', help_text='Page Title (Recommended: 60-70 characters)', max_length=70),
        ),
    ]
