# Generated by Django 5.1.6 on 2025-04-09 11:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogsettings_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, help_text='Upload a banner image for the blog.', null=True, upload_to='blog/banners/')),
                ('title', models.CharField(help_text="The title of the page (e.g., 'About Us'). This will appear in the browser tab and as the H1 tag.", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text="The URL of the page (e.g., 'about-us'). Automatically generated from the title if not provided.", max_length=200, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('page_title', models.CharField(default='', help_text='Page Title (Recommended: 60-70 characters)', max_length=70)),
                ('meta_title', models.CharField(default='', help_text='Meta Title (Recommended: 60-70 characters)', max_length=70)),
                ('meta_description', models.TextField(default='', help_text='Meta Description (Recommended: 150-320 characters)', max_length=320)),
                ('meta_keywords', models.TextField(default='', help_text='Comma-separated keywords (Avoid keyword stuffing)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.AlterModelOptions(
            name='blogsettings',
            options={'verbose_name': 'Blog Setting', 'verbose_name_plural': 'Blogs Settings'},
        ),
    ]
