# Generated by Django 5.1.6 on 2025-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_pages_alter_blogsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='links',
            field=models.TextField(blank=True, help_text='Custom links for the head section', null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='links',
            field=models.TextField(blank=True, help_text='Custom links for the head section', null=True),
        ),
    ]
