# Generated by Django 5.2 on 2025-04-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='accounts_tr_referen_5c4e79_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
    ]
