# Generated by Django 5.1.5 on 2025-02-19 04:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('site_title', models.CharField(default='', max_length=120)),
                ('meta_title', models.CharField(default='', help_text='SEO-friendly title', max_length=160)),
                ('meta_description', models.TextField(default='', help_text='Meta description for SEO')),
                ('meta_keywords', models.TextField(default='', help_text='Comma-separated keywords')),
                ('links', models.TextField(help_text='Custom links for the head section')),
                ('custom_styles', models.TextField(help_text='Additional CSS styles')),
            ],
            options={
                'verbose_name': 'Head Section',
                'verbose_name_plural': 'Head Section',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(default='', max_length=500)),
                ('razorpay_key_secret', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway',
            },
        ),
        migrations.CreateModel(
            name='ProductByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Product By Category',
                'verbose_name_plural': 'Product By Category',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=15)),
                ('site_header_news', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('mobile_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('main_page_image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('main_page_timer_thumbnail', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('main_page_timer_heading', models.CharField(blank=True, max_length=30)),
                ('main_page_timer_caption', models.CharField(blank=True, max_length=30)),
                ('main_page_timer', models.CharField(help_text='Format: dec 25, 2024 15:00:00', max_length=30)),
                ('main_page_timer_url', models.URLField(blank=True)),
                ('main_page_timer_strap_classes', models.CharField(default='bg-red-500', max_length=500)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('instagram_page', models.URLField(blank=True)),
                ('facebook_handle', models.URLField(blank=True)),
                ('twitter_handle', models.URLField(blank=True)),
                ('youtube_handle', models.URLField(blank=True)),
                ('font_style', models.CharField(default='font-sans', help_text='font-sans, font-serif, font-mono or any Custom Class', max_length=80)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='homeSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('products', models.ManyToManyField(to='store.product')),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
            },
        ),
    ]
