# Generated by Django 5.1.6 on 2025-03-14 19:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('site_title', models.CharField(default='', max_length=120)),
                ('meta_title', models.CharField(default='', help_text='SEO-friendly title', max_length=160)),
                ('meta_description', models.TextField(default='', help_text='Meta description for SEO')),
                ('meta_keywords', models.TextField(default='', help_text='Comma-separated keywords')),
                ('links', models.TextField(help_text='Custom links for the head section')),
                ('custom_styles', models.TextField(help_text='Additional CSS styles')),
            ],
            options={
                'verbose_name': 'Head Section',
                'verbose_name_plural': 'Head Section',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text="The URL of the page (e.g., 'about-us'). Automatically generated from the title if not provided.", max_length=200, unique=True)),
                ('title', models.CharField(help_text="The title of the page (e.g., 'About Us'). This will appear in the browser tab and as the H1 tag.", max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='A brief description of the page for SEO purposes (160-300 characters recommended).', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text="Comma-separated keywords for SEO purposes (e.g., 'about us, company, history').", max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('canonical_url', models.URLField(blank=True, help_text="The canonical URL of the page (e.g., 'https://example.com/about-us').", max_length=500)),
                ('og_title', models.CharField(blank=True, help_text="The title of the page for social media sharing (e.g., 'About Us | Company Name').", max_length=200)),
                ('og_description', models.CharField(blank=True, help_text='The description of the page for social media sharing.', max_length=300)),
                ('og_image', models.URLField(blank=True, help_text='The URL of the image to display when the page is shared on social media.', max_length=500)),
                ('twitter_card', models.CharField(blank=True, help_text="The type of Twitter card to use (e.g., 'summary', 'summary_large_image').", max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='The title of the page for Twitter sharing.', max_length=200)),
                ('twitter_description', models.CharField(blank=True, help_text='The description of the page for Twitter sharing.', max_length=300)),
                ('twitter_image', models.URLField(blank=True, help_text='The URL of the image to display when the page is shared on Twitter.', max_length=500)),
                ('structured_data', models.TextField(blank=True, help_text='JSON-LD structured data for rich snippets (e.g., FAQ, Article, Breadcrumb).')),
                ('robots_index', models.BooleanField(default=True, help_text='Whether search engines should index this page.')),
                ('robots_follow', models.BooleanField(default=True, help_text='Whether search engines should follow links on this page.')),
                ('is_published', models.BooleanField(default=True, help_text='Whether the page is published and visible on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(default='', max_length=500)),
                ('razorpay_key_secret', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway',
            },
        ),
        migrations.CreateModel(
            name='ProductByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Product By Category',
                'verbose_name_plural': 'Product By Category',
            },
        ),
        migrations.CreateModel(
            name='SideNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Side Navbar',
                'verbose_name_plural': 'Side Navbars',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=15)),
                ('site_header_news', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('preloader_img', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('mobile_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('main_page_image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('main_page_timer_thumbnail', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('main_page_timer_heading', models.CharField(blank=True, max_length=30)),
                ('main_page_timer_caption', models.CharField(blank=True, max_length=30)),
                ('main_page_timer', models.CharField(help_text='Format: dec 25, 2024 15:00:00', max_length=30)),
                ('main_page_timer_url', models.URLField(blank=True)),
                ('main_page_timer_strap_classes', models.CharField(default='bg-red-500', max_length=500)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('instagram_page', models.URLField(blank=True)),
                ('facebook_handle', models.URLField(blank=True)),
                ('twitter_handle', models.URLField(blank=True)),
                ('youtube_handle', models.URLField(blank=True)),
                ('font_style', models.CharField(default='font-sans', help_text='font-sans, font-serif, font-mono or any Custom Class', max_length=80)),
                ('login_banner', models.ImageField(blank=True, null=True, upload_to='login/')),
                ('login_banner_desktop', models.ImageField(blank=True, null=True, upload_to='login/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('url', models.URLField(blank=True)),
                ('is_mobile', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='homeSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('products', models.ManyToManyField(to='store.product')),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
            },
        ),
    ]
