# Generated by Django 5.1.5 on 2025-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
