# Generated by Django 5.1.6 on 2025-03-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_featured_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesections',
            name='heading',
            field=models.CharField(default='', max_length=50),
        ),
    ]
