# Generated by Django 5.1.6 on 2025-03-26 23:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homesections_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='product_return_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
