# Generated by Django 5.1.5 on 2025-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='preloader_img',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
