# Generated by Django 5.1.6 on 2025-03-26 23:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sitesettings_product_return_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_return_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Product Return Details'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_header_news',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Site Header News'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_news',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Slider News'),
        ),
    ]
