# Generated by Django 5.1.6 on 2025-03-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_page_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gst_percentage',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
