# Generated by Django 5.1.5 on 2025-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sitesettings_preloader_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Side Navbar',
                'verbose_name_plural': 'Side Navbars',
            },
        ),
    ]
