# Generated by Django 5.1.5 on 2025-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sidenav'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidenav',
            name='logo_svg',
            field=models.TextField(default=''),
        ),
    ]
