# Generated by Django 5.1.6 on 2025-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sitesettings_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_categories',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
