# Generated by Django 5.1.6 on 2025-04-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_featured_categories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_categories',
            name='url',
        ),
    ]
