# Generated by Django 5.1.5 on 2025-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sidenav_logo_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidenav',
            name='logo_svg',
        ),
        migrations.AddField(
            model_name='sidenav',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
