# Generated by Django 5.1.6 on 2025-04-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_featured_categories_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_logo',
        ),
    ]
