# Generated by Django 5.1.5 on 2025-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_sidenav_logo_svg_sidenav_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidenav',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='sidenav',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
