# Generated by Django 5.1.6 on 2025-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_sitesettings_mobile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_height',
            field=models.IntegerField(default=72, help_text='size in px'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_width',
            field=models.IntegerField(default=144, help_text='size in px'),
        ),
    ]
