# Generated by Django 5.1.6 on 2025-04-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sitesettings_logo_height_sitesettings_logo_width'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
