# Generated by Django 5.1.6 on 2025-04-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_paymentgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidenav',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
