# Generated by Django 5.1.6 on 2025-04-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_sidenav_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='page',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='robots_follow',
        ),
        migrations.RemoveField(
            model_name='page',
            name='robots_index',
        ),
        migrations.RemoveField(
            model_name='page',
            name='twitter_card',
        ),
        migrations.RemoveField(
            model_name='page',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='twitter_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='twitter_title',
        ),
    ]
