# Generated by Django 5.1.6 on 2025-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_page_canonical_url_remove_page_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='links',
            field=models.TextField(blank=True, help_text='Custom links for the head section', null=True),
        ),
    ]
