# Generated by Django 5.1.6 on 2025-04-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_page_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='instagram_page',
            new_name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram',
        ),
    ]
