# Generated by Django 5.1.6 on 2025-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_instagram_page_sitesettings_instagram_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_image_url',
            field=models.URLField(blank=True),
        ),
    ]
