# Generated by Django 5.1.5 on 2025-02-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider1_caption1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider1_caption2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider1_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider1_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider2_caption1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider2_caption2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider2_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider2_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider3_caption1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider3_caption2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider3_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider3_url',
        ),
    ]
