# Generated by Django 5.1.5 on 2025-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_sitesettings_slider1_caption1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
            },
        ),
    ]
