# Generated by Django 5.1.5 on 2025-02-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homesections'),
        ('store', '0005_auto_20210321_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesections',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
