# Generated by Django 5.1.5 on 2025-02-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homesections_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesections',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
