# Generated by Django 5.1.5 on 2025-02-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homesections_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='main_page_video_thumbnail',
            new_name='main_page_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='main_page_video_caption',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='main_page_video_url',
        ),
    ]
