# Generated by Django 5.1.5 on 2025-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_main_page_video_thumbnail_sitesettings_main_page_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_price',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_timer_heading',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
