# Generated by Django 5.1.5 on 2025-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_sitesettings_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='main_page_timer_url',
            field=models.URLField(blank=True),
        ),
    ]
