# Generated by Django 5.1.5 on 2025-02-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_sitesettings_main_page_timer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField()),
                ('custom_styles', models.TextField()),
            ],
            options={
                'verbose_name': 'Head Section',
                'verbose_name_plural': 'Head Section',
            },
        ),
    ]
