# Generated by Django 5.1.5 on 2025-02-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_headsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='font_style',
            field=models.CharField(default='font-sans', help_text='font-sans, font-serif, font-mono or any Custom Class', max_length=10),
        ),
    ]
