# Generated by Django 5.1.5 on 2025-02-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_sitesettings_font_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='main_page_timer',
            field=models.CharField(help_text='Format: dec 25, 2024 15:00:00', max_length=30),
        ),
    ]
