# Generated by Django 5.1.5 on 2025-02-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_sitesettings_main_page_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_timer_strap_classes',
            field=models.CharField(default='bg-red-500', max_length=500),
        ),
    ]
