# Generated by Django 5.1.5 on 2025-02-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_sitesettings_main_page_timer_strap_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='slider_background_color',
        ),
        migrations.AddField(
            model_name='headsection',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='headsection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='headsection',
            name='meta_description',
            field=models.TextField(default='', help_text='Meta description for SEO'),
        ),
        migrations.AddField(
            model_name='headsection',
            name='meta_keywords',
            field=models.TextField(default='', help_text='Comma-separated keywords'),
        ),
        migrations.AddField(
            model_name='headsection',
            name='meta_title',
            field=models.CharField(default='', help_text='SEO-friendly title', max_length=160),
        ),
        migrations.AddField(
            model_name='headsection',
            name='site_title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='headsection',
            name='custom_styles',
            field=models.TextField(help_text='Additional CSS styles'),
        ),
        migrations.AlterField(
            model_name='headsection',
            name='links',
            field=models.TextField(help_text='Custom links for the head section'),
        ),
    ]
