# Generated by Django 5.1.6 on 2025-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='not_found_searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('name', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Not Found Search',
                'verbose_name_plural': 'Not found Searches',
            },
        ),
        migrations.CreateModel(
            name='search_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('url', models.URLField(blank=True)),
                ('name', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Search Category',
                'verbose_name_plural': 'Search Categories',
            },
        ),
        migrations.CreateModel(
            name='top_searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('name', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Top Search',
                'verbose_name_plural': 'Top Searches',
            },
        ),
    ]
