# Generated by Django 5.1.6 on 2025-03-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search_categories',
        ),
        migrations.RemoveField(
            model_name='not_found_searches',
            name='url',
        ),
        migrations.RemoveField(
            model_name='top_searches',
            name='url',
        ),
    ]
