# Generated by Django 5.1.5 on 2025-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('PAYU', 'PAYU'), ('RAZORPAY', 'RAZORPAY')], max_length=10)),
                ('razorpay_id', models.CharField(default='', max_length=500)),
                ('razorpay_secret', models.CharField(default='', max_length=500)),
                ('payu_marchent_key', models.CharField(default='', max_length=500)),
                ('payu_marchent_salt', models.CharField(default='', max_length=500)),
                ('mode', models.CharField(help_text='LIVE or TEST', max_length=10)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
