# Generated by Django 5.1.6 on 2025-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='contact_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='order/paymentgateway'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='use',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('PAYU', 'PAYU'), ('RAZORPAY', 'RAZORPAY')], max_length=10),
        ),
    ]
