# Generated by Django 5.1.6 on 2025-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('smtp', 'SMTP'), ('console', 'Console (for testing)'), ('file', 'File (for testing)')], default='smtp', help_text='Backend to use for sending emails', max_length=50)),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server address', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587, help_text='SMTP server port')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Whether to use TLS (secure) connection')),
                ('email_host_user', models.EmailField(help_text='Email address used to send emails', max_length=255)),
                ('email_host_password', models.CharField(blank=True, help_text='Password for the email account', max_length=255)),
                ('default_from_email', models.EmailField(help_text="Default 'from' address for emails", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these settings are active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
