# Generated by Django 5.1.6 on 2025-04-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_siteads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteAds',
            new_name='SiteNotifications',
        ),
    ]
