# Generated by Django 5.1.6 on 2025-04-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_siteads_sitenotifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitenotifications',
            options={'verbose_name': 'Site Notification', 'verbose_name_plural': 'Site Notifications'},
        ),
    ]
